# Generated by Django 5.0.6 on 2024-09-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Resolved', 'Resolved'), ('Unresolved', 'Unresolved')], default='Open', max_length=100),
        ),
    ]
