# Generated by Django 5.0.6 on 2024-09-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
